language: node_js
node_js: 14
# every second counts
git:
  depth: 5
services: docker
env:
  - NODE_ENV=production
# We no longer use npm, and I cba yarn since this really never builds
#cache:
#  directories:
#    - $HOME/.npm
install:
  - yarn --production=false
script:
  - yarn test:once --maxWorkers=2
  - docker build --tag wowanalyzer-server .
# Reminder: deploy doesn't run on PRs
deploy:
  provider: script
  skip_cleanup: true
  script: bash .travis/deploy.sh
  on:
    all_branches: true
after_failure:
  - chmod +x .travis/discord-hook/fail.sh
  - ./.travis/discord-hook/fail.sh
notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never
