version: '3'

volumes:
  database_data: {}

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app/
      # Use the node_modules in the container for greatly improved performance on Windows machines. This does mean you need to run either `docker-compose build server` or `docker-compose exec server pnpm install` when setting up new dependencies.
      - /usr/src/app/node_modules/
    environment:
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
      - MYSQL_DIALECT=mariadb
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=wowanalyzer
    depends_on:
      - database
      - cache

  database:
    image: mariadb:10.3
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--lower_case_table_names=0', '--max_allowed_packet=16M']
    volumes:
      - database_data:/var/lib/mysql:rw
    environment:
     - MYSQL_ROOT_PASSWORD=my-secret-pw
     - MYSQL_DATABASE=wowanalyzer
    restart: always
    ports:
     - 3306:3306

  cache:
    image: memcached:1.6-alpine
    ports:
      - 11211:11211
    command: '-I 5M'
