name: 'Build'

on: [push, pull_request]

env:
  CI: true
  DOCKER_BUILD_TAG: build-${{ github.run_number }}

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # TODO: tests?
      - run: docker build --tag wowanalyzer-server .
      - run: bash .github/workflows/deploy.sh
        if: github.event_name != 'pull_request' && github.repository == 'wowanalyzer/server'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
